name: Heroku spring boot Deployment
on:
  push:
    branches: [ main ]
jobs:
  build:
runs-on: ubuntu-latest
steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.SBHEROKU_API_KEY}}
        heroku_email: ${{secrets.SBHEROKU_EMAIL}}
        heroku_app_name: ${{secrets.SBHEROKU_APP}}
